### ISSUE TITLE
Email IRIs are not valid `iri-reference`

### ISSUE THREAD

**Issue by egekorkan** [luzlab/ajv-formats-draft2019#18]
The following simple script does not work:
```js
const Ajv = require('ajv');
const apply = require('ajv-formats-draft2019');
const ajv = new Ajv();
apply(ajv); // returns ajv instance, allowing chaining

let schema = {
  type: 'string',
  format: 'iri-reference'
};
let result = ajv.validate(schema, 'mailto:John.Doe@example.com');

console.log (result)
```

With @FadySalama, we have dug deeper into the issue and find the following problems:
- The test at https://github.com/luzlab/ajv-formats-draft2019/blob/465607edac0109af366123a821ff3226689a3ba6/index.test.js#L283 is actually checking for invalidity
- When we use the debugger, we get `"addressParser is not a function"` at validate of https://github.com/luzlab/ajv-formats-draft2019/blob/465607edac0109af366123a821ff3226689a3ba6/formats/iri-reference.js#L2  
- When we change it to `const AddressParser = require('smtp-address-parser').parse;` , everything works

**Comment by luzlab** [comment]
resolved

**Comment by egekorkan** [comment]
Thanks! Could you also publish a new version on npm?

**Comment by luzlab** [comment]
Hi Ege - Yes, I'm having some trouble logging into my npmjs account. I've
reached out for help.

C

**Comment by carlo-quinonez** [comment]
It seems like NPM support might unlock my account next week. I had to reach out to a friend @securingdev at github to help get some traction with npm support.
