### ISSUE TITLE
S3 and other IRI

### ISSUE THREAD

**Issue by m-mohr** [luzlab/ajv-formats-draft2019#4]
I have a valid S3 bucket URI: `s3://cbers-pds/CBERS4/MUX/177/106/CBERS_4_MUX_20181029_177_106_L4/CBERS_4_MUX_20181029_177_106_L4_BAND5.tif`

Unfortunately, it is rejected by this library.

I guess it's due to the fact that schemes on npm is outdated. Is there a way to disabled the schemes check?

**Comment by carlo-quinonez** [comment]
@m-mohr I'm sorry for the slow response. I've created an [issue](https://github.com/Munter/schemes/issues/16) for the module I'm using as the list of valid schemes.

Let's give the maintainers of that package some time to respond.

**Comment by m-mohr** [comment]
Thanks! The issue is that any protocol may come up in our case, but I first found it with S3. We also have use cases for other cloud storage providers, e.g., gs:// for Google Cloud Storage.

**Comment by luzlab** [comment]
The `schemes` maintainer already merged the PR adding `s3` as a valid scheme. If you want to add more public schemes, then it's probably best to submit a PR to that repo with any new schemes so this problem is solved for everyone.

**Comment by m-mohr** [comment]
Yes, indeed. Thanks.

**Comment by luzlab** [comment]
Let me know when your PR to `schemes` gets merged and I'll update the dependency.

**Comment by carlo-quinonez** [comment]
@m-mohr I saw you made a PR on the `schemes` repo but it was never merged. I just opened an issue Munter/schemes#19 just in case the maintainer didn't notice your PR...

**Comment by m-mohr** [comment]
Thanks for the heads-up. The PR was merged some days ago.

**Comment by luzlab** [comment]
@m-mohr  Did this fix your use-case? I believe if you re-install this module, it should pull in the latest version of the `schemes` module.

**Comment by m-mohr** [comment]
Yes, thanks!
