### ISSUE TITLE
Failing test on Node 10

### ISSUE THREAD

**Issue by carlo-quinonez** [luzlab/ajv-formats-draft2019#8]
After merging the `smtp-address-parser` PR, the tests failed on Node 10.

@gene-hightower Can you please fix this in your module? Otherwise, I'm going to revert the changes. Sorry I should have setup the GH action to run the tests BEFORE I merged the PR...

**Comment by gene-hightower** [comment]
I'll take a look...

**Comment by gene-hightower** [comment]
I have published a new version of smtp-address-parser (1.0.3) which should work with Node 10 (es2018). @carlo-quinonez Can you give it a try?

**Comment by gene-hightower** [comment]
@carlo-quinonez should I open a PR with the updated version number for smtp-address-parser?

**Comment by luzlab** [comment]
I can update the version. Thank you!

**Comment by luzlab** [comment]
All tests are passing. I added a test for Node v8 as well.

Thank you @gene-hightower
