### ISSUE TITLE
"validate" is not defined in iri-refernces.js

### ISSUE THREAD

**Issue by FadySalama** [luzlab/ajv-formats-draft2019#9]
The function `validate` is not defined in iri-references.js https://github.com/luzlab/ajv-formats-draft2019/blob/2344389823bc6f082412610f40c79fe8a997dc1d/formats/iri-reference.js#L7

This causes a problem when a `mailto:`-iri is being validated

**Comment by luzlab** [comment]
Thank you for catching that! That's an embarrassing oversight on my part.
